name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  Build-and-Tests:
    name: Build and Test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: running kafka
      run: |
        cd kafka
        docker-compose up -d
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: logging kafka
      run: |
        cd kafka
        docker-compose logs            
    - name: set pythonpath
      run: |
        echo "PYTHONPATH=./src:${PYTHONPATH}" >> $GITHUB_ENV        
    - name: Test
      run: |	  
        pytest --junitxml=report.xml
        coverage run --source src --branch -m pytest
        coverage xml
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.4
      with:
        reports: 'coverage.xml'
        targetdir: 'docs' # REQUIRED # The directory where the generated report should be saved.
        sourcedirs: 'src' 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path: docs
        retention-days: 90  
    - name: Push Report
      uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
      with:
        add: 'docs/*'
        message: 'Coverage Report ${GITHUB_SHA}' 
        ref: 'gh-pages' 
        remove: ''  
    - name: Publish Unit Test Results
      uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: report.xml
